name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - master      
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0

    - name: Restore dependencies
      run: dotnet restore

    - name: Build application
      run: dotnet build --no-restore --configuration Release
      
    - name: Build Test Project
      run: dotnet build StoreManagement.Tests/StoreManagement.Tests.csproj --configuration Debug

    - name: List output files
      run: dir ${{ github.workspace }}\StoreManagement.Tests\bin\Debug\net6.0-windows

    - name: Run Unit Tests
      run: dotnet test StoreManagement.Tests/StoreManagement.Tests.csproj --no-build --verbosity normal
