name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - master      
  pull_request:
    branches:
      - main
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0  # Đổi thành phiên bản .NET của bạn

    - name: Restore dependencies
      run: dotnet restore

    - name: Build application
      run: dotnet build --no-restore --configuration Release
